from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path
from . import views
from .views import order_invoice

urlpatterns=[
    path("", views.index),
    path("about/", views.about),
    path("service/", views.service),
    path("shop/",views.shop),
    path("login/", views.login_view),
    path("signup/", views.signup),
    path("save_reg/", views.save_reg),
    path("check_log/",views.check_log),
    path("cart/",views.cart),
    path("admin_home/",views.admin_home,name="admin_home"),
    path("categories/",views.categories),
    path("add_category/",views.add_category),
    path("save_category/",views.save_category),
    path("edit_category/<cat_id>",views.edit_category),
    path("update_category/<cat_id>",views.update_category),
    path("delete_category/<cat_id>",views.delete_category),
    path("sub_categories/",views.sub_categories),
    path("add_subcategory/",views.add_subcategory),
    path("save_subcategory/",views.save_subcategory),
    path("edit_subcategory/<subcat_id>",views.edit_subcategory),
    path("update_subcategory/<subcat_id>",views.update_subcategory),
    path("delete_subcategory/<subcat_id>",views.delete_subcategory),
    path("products/",views.products),
    path("add_product/",views.add_product),
    path("save_product/",views.save_product),
    path("edit_product/<prod_id>",views.edit_product),
    path("update_product/<prod_id>",views.update_product),
    path("delete_product/<prod_id>",views.delete_product),
    path("cart_delete/<pro_id>",views.cart_delete),
    path("coupons/",views.coupons),
    path("add_coupon/",views.add_coupon),
    path("save_coupon/",views.save_coupon),
    path("edit_coupon/<code_id>",views.edit_coupon),
    path("update_coupon/<code_id>",views.update_coupon),
    path("delete_coupon/<code_id>",views.delete_coupon),
    path("single_product/<prod_id>",views.single_product),
    path("add_to_cart/",views.add_to_cart),
    path("update_cart_qty/",views.update_cart_qty),
    path("buy_now/<prod_id>",views.buy_now),
    path('create_razorpay_order/',views.create_razorpay_order),
    path("check_coupon/",views.check_coupon),
    path("checkout_buy/<pro_id>",views.checkout_buy),
    path("cart_buynow/",views.cart_buynow),
    path("checkout_cart/",views.checkout_cart),
    path("profile/",views.profile),
    path("log_out/",views.log_out),
    path("add_address/",views.add_address),
    path("update_account/",views.update_account),
    path("add_review/",views.add_review),
    path("stock_updates/",views.stock_update),
    path("save_stock/",views.save_stock),
    path("inventory_report/",views.inventory_report),
    path("search_month/",views.search_month),
    path("search_date/",views.search_date),
    path("search_sku/",views.search_sku),
    path("search_product/",views.search_product),
    path("search_cate/",views.search_cate),
    path("export_inventory_report/",views.export_inventory_report),
    path("order_management/",views.order_management),
    path("cart-order-items/<order_id>/",views.cart_order_items),
    path("change_status/<order_id>",views.change_status),
    path("order_delete/<order_id>",views.order_delete),
    path("order_invoice/<order_id>",views.order_invoice,name="order_invoice"),
    path("user_review/",views.user_review),
    path("delete_review/<review_id>",views.delete_review),
    path("sales_report/",views.sales_report),
    path("searchby_user/",views.searchby_user),
    path("searchby_product/",views.searchby_product),
    path("searchby_status/", views.searchby_status),
    path("export_sales_report/", views.export_sales_report),
    path("shop_subcat/<pro_id>/", views.shop_subcat, name="shop_subcat"),
    path("admin_signout/",views.admin_signout),

]