# Generated by Django 5.2.9 on 2025-12-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tablereg',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
