# Generated by Django 5.2.9 on 2025-12-29 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0002_tablecategory_alter_tablereg_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablecategory',
            old_name='name',
            new_name='category',
        ),
    ]
