# Generated by Django 5.2.9 on 2025-12-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0003_rename_name_tablecategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecategory',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='TableSubclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablecategory')),
            ],
        ),
    ]
