# Generated by Django 5.2.9 on 2025-12-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0004_alter_tablecategory_image_tablesubclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesubclass',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
