# Generated by Django 5.2.9 on 2025-12-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0005_alter_tablesubclass_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableSubclass',
            new_name='TableSubcategory',
        ),
    ]
