# Generated by Django 5.2.9 on 2026-01-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0006_rename_tablesubclass_tablesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('slug', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('subcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablesubcategory')),
            ],
        ),
    ]
