# Generated by Django 5.2.9 on 2026-01-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0007_tableproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
