# Generated by Django 5.2.9 on 2026-01-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0008_tablecoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('session_key', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tableproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablereg')),
            ],
        ),
    ]
