# Generated by Django 5.2.9 on 2026-01-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0010_tableaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableaddress',
            old_name='pc',
            new_name='pincode',
        ),
        migrations.AddField(
            model_name='tableaddress',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TableBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('disc_price', models.FloatField(null=True)),
                ('orderID', models.CharField(max_length=100, null=True)),
                ('paymentID', models.CharField(max_length=100, null=True)),
                ('order_status', models.CharField(max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=100, null=True)),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('invoiceID', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tableaddress')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablecoupon')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tableproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablereg')),
            ],
        ),
    ]
