# Generated by Django 5.2.9 on 2026-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0011_rename_pc_tableaddress_pincode_tableaddress_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableproduct',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
