# Generated by Django 5.2.9 on 2026-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0012_tableproduct_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
