# Generated by Django 5.2.9 on 2026-01-15 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0013_alter_tableproduct_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCheckoutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablebuy')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tableproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablereg')),
            ],
        ),
    ]
