# Generated by Django 5.2.9 on 2026-01-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0014_tablecheckoutlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableproduct',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tableproduct',
            name='sku_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TableReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='media')),
                ('image2', models.ImageField(null=True, upload_to='media')),
                ('rating', models.IntegerField(null=True)),
                ('review', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tableproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablereg')),
            ],
        ),
    ]
