# Generated by Django 5.2.9 on 2026-01-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projectAPP', '0015_tableproduct_date_tableproduct_sku_code_tablereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_projectAPP.tablecategory'),
        ),
    ]
